entrance = "search"
main_page = "https://www.javbus.com/"

[[actions]]
  type = "group"
  name = "search"
  index = 0
  through = false
  on_success = "detail"
  on_failure = ""
  [actions.web]
    method = "GET"
    uri = "search"
    selector = "div > a.movie-box"
  [actions.success]
    name = "nexturl"
    trim = true
    type = "put"
    property = "attr"

[[actions]]
  type = ""
  name = "detail"
  index = 2
  through = false
  on_success = ""
  on_failure = ""
  [actions.web]
    method = "GET"
    url = "test url"
    uri = "test uri"
    selector = ""
    [actions.web.header]
      cookie = ["2"]
  [actions.step]
    type = "none2"
