entrance = "search"
main_page = "https://www.javbus.com/"

[[actions]]
  type = "group"
  name = "search"
  index = 0
  through = false
  on_success = "detail"
  on_failure = ""
  [actions.web]
    method = "GET"
    relative = true
    value = ["/search"]
    selector = "div > a.movie-box"
  [[actions.web.success]]
    name = "nexturl"
    trim = true
    type = "put"
    property = "attr"
    property_name = "href"

[[actions]]
  type = ""
  name = "detail"
  index = 1
  through = false
  on_success = ""
  on_failure = ""
  [actions.web]
    method = "GET"
      relative = false
      skip = ["input"]
      value = ["$nexturl"]
#     url = "test url"
#     uri = "test uri"
    selector = "body > div.container"
  [[actions.web.success]]
    selector = "h3"
    name = "title"
    trim = true
    type = "put"
    property = "value"

  [[actions.web.success]]
    selector = "div.row.movie > div.col-md-3.info > p"
#     filter = ["span.header"]
    index = 0
    name = "code_no"
    trim = true
    type = "put"
    property = "value"
    [[actions.web.success]]
      selector = "div.row.movie > div.col-md-3.info > p"
#       filter = ["span.header"]
      index = 1
      name = "release"
      trim = true
      type = "put"
      property = "value"

    [[actions.web.success]]
      selector = "div.row.movie > div.col-md-3.info > p"
#       filter = ["span.header"]
      index = 2
      name = "length"
      trim = true
      type = "put"
      property = "value"

    [[actions.web.success]]
      selector = "div.row.movie > div.col-md-3.info > p"
#       filter = ["span.header"]
      index = 3
      name = "studio"
      trim = true
      type = "put"
      property = "value"

      [[actions.web.success]]
        selector = "div.row.movie > div.col-md-3.info > p"
  #       filter = ["span.header"]
        index = 4
        name = "label"
        trim = true
        type = "put"
        property = "value"

      [[actions.web.success]]
        selector = "div.row.movie > div.col-md-3.info > p"
  #       filter = ["span.header"]
        index = 5
        name = "series"
        trim = true
        type = "put"
        property = "value"

     [[actions.web.success]]
       selector = "div.row.movie > div.col-md-3.info > p"
 #       filter = ["span.header"]
       index = 7
       name = "genre"
       trim = true
       type = "put"
       property = "array"

          [[actions.web.success]]
            selector = "div.row.movie > div.col-md-3.info > p"
      #       filter = ["span.header"]
            index = 9
            name = "star"
            trim = true
            type = "put"
            property = "array"

[[actions]]
  type = ""
  name = "finish"
  index = 2
  through = false
  on_success = ""
  on_failure = ""
  [actions.web]
    method = "GET"
    url = "test url"
    uri = "test uri"
    selector = ""
