entrance = "search"
main_page = "https://www.javbus.com/"

[[actions]]
  type = "group"
  name = "search"
  index = 0
  through = false
  on_success = "detail"
  on_failure = ""
  [actions.web]
    method = "GET"
    relative = true
    value = ["/search"]
    selector = "div > a.movie-box"
  [[actions.web.success]]
    name = "nexturl"
    trim = true
    type = "put"
    property = "attr"
    property_name = "href"

[[actions]]
  type = ""
  name = "detail"
  index = 1
  through = false
  on_success = ""
  on_failure = ""
  [actions.web]
    method = "GET"
      relative = false
      skip = ["input", "main"]
      from_value = ["nexturl"]
#     url = "test url"
#     uri = "test uri"
    selector = "body > div.container > div.row.movie"
    [actions.web.header]
      cookie = ["2"]
  [actions.step]
    type = "none2"


[[actions]]
  type = ""
  name = "finish"
  index = 2
  through = false
  on_success = ""
  on_failure = ""
  [actions.web]
    method = "GET"
    url = "test url"
    uri = "test uri"
    selector = ""
